DefiBundle\Entity\uploads:
    type: entity
    table: null
    repositoryClass: DefiBundle\Repository\uploadsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        uploads:
            type: string
            length: 255
            nullable: true

    lifecycleCallbacks:
        prePersist: [ preUpload ]
        preUpdate: [ preUpload ]
        postPersist: [ upload ]
        postUpdate: [ upload ]
        postRemove: [ removeUpload ]
