DefiBundle\Entity\Utilisateurs:
    type: entity
    table: null
    repositoryClass: DefiBundle\Repository\UtilisateursRepository
    id:
        idUtilisateurs:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        pseudo:
            type: string
            length: '30'
            unique: true
            nullable: true
        sexe:
            type: string
            length: '1'
            nullable: true
        dateNaissance:
            type: date
            nullable: true
            column: date_naissance
        photoProfil:
            type: string
            length: 255
            column: photo_profil


    manyToMany:
            fidtrophees:
                targetEntity: DefiBundle\Entity\Trophees
                inversedBy: Utilisateurs
                joinTable:
                    name: Trophees_utilisateurs
                    joinColumns:
                        Utilisateurs_id:
                            referencedColumnName: id_utilisateurs
                    inverseJoinColumns:
                        Trophees_id:
                            referencedColumnName: id_trophees


            fidUtilisateurs:
                targetEntity: DefiBundle\Entity\Sport
                mappedBy: Utilisateurs


    lifecycleCallbacks: {  }
