DefiBundle\Entity\Utilisateurs:
    type: entity
    table: null
    repositoryClass: DefiBundle\Repository\UtilisateursRepository
    id:
       id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        pseudo:
            type: string
            length: '30'
            unique: true
            nullable: true
        sexe:
            type: string
            length: '1'
            nullable: true
        dateNaissance:
            type: date
            nullable: true
            column: date_naissance
        photoProfil:
            type: text
            length: 255
            column: photo_profil
            nullable: true



    manyToMany:
        fidtrophees:
            targetEntity: DefiBundle\Entity\Trophees
            inversedBy: Utilisateurs
            joinTable:
                name: Trophees_utilisateurs
                joinColumns:
                    Utilisateurs_id:
                        referencedColumn: id
                inverseJoinColumns:
                    Trophees_id:
                        referencedColumnName: id_trophees

        fidSport:
            targetEntity: Sport
            inversedBy: Utilisateurs
            joinTable:
                name: Utilisateurs_Sport
                joinColumns:
                    Utilisateurs_id:
                        referencedColumn: id
                inverseJoinColumns:
                    Sport_id:
                        referencedColumnName: id_sport

    lifecycleCallbacks: {  }
