<?php

namespace DefiBundle\Repository;

/**
 * TropheesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TropheesRepository extends \Doctrine\ORM\EntityRepository
{
}
