<?php

namespace DefiBundle\Repository;

/**
 * uploadsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class uploadsRepository extends \Doctrine\ORM\EntityRepository
{
}
